Models/ErrorViewModel.cs
namespace DependencyInjection.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/OperationsController.cs
using DependencyInjection.Services;
using Microsoft.AspNetCore.Mvc;

namespace DependencyInjection.Controllers
{
    public class OperationsController : Controller
    {
        private readonly OperationService _operationService;
        private readonly IOperationTransient _transientOperation;
        private readonly IOperationScoped _scopedOperation;
        private readonly IOperationSingleton _singletonOperation;
        
        public OperationsController(OperationService operationService, IOperationTransient transientOperation, IOperationScoped scopedOperation, IOperationSingleton singletonOperation)
        {
            _operationService = operationService;
            _transientOperation = transientOperation;
            _scopedOperation = scopedOperation;
            _singletonOperation = singletonOperation;
        }

        public IActionResult Index()
        {
            OperationsProcess();
            return View();
        }

        public IActionResult GetOperations()
        {
            OperationsProcess();
            return PartialView("_OperationsPartial");
        }

        private void OperationsProcess()
        {
            // ViewBag contains controller-requested services
            ViewBag.Transient = _transientOperation.OperationId.ToString();
            ViewBag.Scoped = _scopedOperation.OperationId.ToString();
            ViewBag.Singleton = _singletonOperation.OperationId.ToString();

            // Operation service has its own requested services
            ViewBag.Transient2 = _operationService.TransientOperation.OperationId.ToString();
            ViewBag.Scoped2 = _operationService.ScopedOperation.OperationId.ToString();
            ViewBag.Singleton2 = _operationService.SingletonOperation.OperationId.ToString();
        }
    }
}

Views/Operations/Index.cshtml
@{
    ViewData["Title"] = "LifeCycles in ASP.NET Core";
}

@section Styles{
    <style>
        .TransientColor {
            background-color: #fff59c !important
        }

        .ScopedColor {
            background-color: aquamarine !important
        }

        .SingletonColor {
            background-color: #ff292991 !important
        }
    </style>
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <strong>LifeCycles in ASP.NET Core</strong>.</p>
    <h6>Understanding <strong class="TransientColor">AddTransient</strong> Vs <strong class="ScopedColor">AddScoped</strong> Vs <strong class="SingletonColor">AddSingleton</strong> In ASP.NET Core</h6>
</div>

<hr />

<table class="table table-bordered text-center">
    <thead>
        <tr>
            <th>Service Type</th>
            <th>Controller Operation</th>
            <th>Service Operation</th>
        </tr>
    </thead>
    <tbody id="OperationsBlock">
        <partial name="_OperationsPartial" />
    </tbody>
</table>


@section Scripts
    {
    <script>
        (function worker() {
            $.ajax({
                url: '/Operations/GetOperations',
                success: function (data) {
                    $('#OperationsBlock').html(data);
                },
                complete: function () {
                    // Schedule the next request when the current one's complete
                    setTimeout(worker, 3000);
                }
            });
        })();
    </script>
}

Views/Operations/_OperationsPartial.cshtml
<tr>
    <td class="TransientColor">Transient </td>
    <td class="TransientColor">@ViewBag.Transient</td>
    <td class="TransientColor">@ViewBag.Transient2</td>
</tr>
<tr>
    <td class="ScopedColor">Scoped</td>
    <td class="ScopedColor">@ViewBag.Scoped</td>
    <td class="ScopedColor">@ViewBag.Scoped2</td>
</tr>
<tr>
    <td class="SingletonColor">Singleton</td>
    <td class="SingletonColor">@ViewBag.Singleton</td>
    <td class="SingletonColor">@ViewBag.Singleton2</td>
</tr>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DependencyInjection</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DependencyInjection.styles.css" asp-append-version="true" />
    
    @await RenderSectionAsync("Styles", required: false)

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Operations" asp-action="Index">DependencyInjection</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
               
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - DependencyInjection
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>